### ISSUE TITLE
Xdev-ify this repository

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/CESM_catalog#1]
Set up admin accounts, add the xdev bot, etc (find out if there is an etc or if it's just those two things)

**Comment by mnlevy1981** [comment]
@NCAR/xdev-cataloging has admin rights, and I invited the bot (maybe @kmpaul needs to accept that invite?).

**Comment by andersy005** [comment]
@mnlevy1981, I just added the bot configurations, and accepted the invitation. The bot should be able to manage issues/PRs moving forward.

**Comment by mnlevy1981** [comment]
Awesome, thanks @andersy005 !
